steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/gothic-depth-456114-c3/gua-gua-bot-worker",
        "-f",
        "worker/Dockerfile.worker",
        ".",
      ]
images:
  - "gcr.io/gothic-depth-456114-c3/gua-gua-bot-worker"
